spring:
  datasource:
    url: jdbc:mysql://localhost:3306/data-collection
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    # 配置数据库
    database: mysql
     #查询是否显示日志
    show-sql: true
    hibernate:
      # Hibernate ddl auto (create, create-drop, update)
      ddl-auto: update
      # Naming strategy
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
          hibernate:
            dialect:org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false

  # 邮件配置
  mail:
    host: smtp.qq.com
    username: 2368311551@qq.com
    #上面获取设置的授权码(POP3/SMTP)  换用你自己在 QQ 邮箱中设置的授权码
    password: negwxcbdstnmeaib
    default-encoding: UTF-8
    protocol: smtp

server:
  tomcat:
    uri-encoding: utf-8
  port: 8080






